<a href="https://colab.research.google.com/github/mokymok/notebooks/blob/main/'CodingInterview'_Tips_and_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Some quick notes before starting

When iterating over an array of `m*n` cells, you can use two nested `for` loops, with `m` being rows and `n` being columns.

In [ ]:
for i in range(m):
    for j in range(n):
        do_stuff(i,j)

However, you can make this significantly smaller by iterating over the Cartesian product of these two ranges and parsing out `m` and `n` inside the loop.  This works by effectively encoding the pair `(i,j)` as `k=i*n+j`.  It's worth noting that it may be helpful to assign `i` and `j` inside the loop as `i=k//n` and `j=k%n` respectively.

In [ ]:
for k in range(m*n):
  do_stuff(k//n,k%n)

This can also be extended to a triple nested `for` loop, encoding the set `(i,j,h)` as `k=(i*n+j)p+h`.  Again, it's worth noting that assigning `i=k//n//p`, `j=k%(n*p)//p`, and `h=k%p` inside the loop may be helpful.

In [ ]:
for k in range(m*n*p):
    do_stuff(k//n//p,k%(n*p)//p,k%p)

# Problem 1

With all that being said, here's a sample problem that some YouTubers did. 
    *(One is a Senior Software Developer at Google, has given these interviews plenty of times.)*


Given an array of integers `nums` and an integer `target`, return the indices of the two numbers such that they add up to the target.

In [ ]:
intArray = []
targetInt = x
for k in range(m * n):
    i = k // n
    j = k % n
    if i + j = x:
        print(m)

In [ ]:
import random
import numpy as np

intArray = np.random.randint(20, size=(15, 6))
targetInt = 14
for numOne in intArray:
    for numTwo in intArray:
        targetArray = (targetInt == numOne + numTwo)
        print(np.where(targetArray))

(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([4]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([4]),)
(array([2]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([4]),)
(array([4]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([0]),)
(arr

In [ ]:
m = 12
n = 51
x = 54
for k in range((m*n)):
    i = k // n
    j = k % n
    if i + j == x:
        print(f"({i},{j})")

(4,50)
(5,49)
(6,48)
(7,47)
(8,46)
(9,45)
(10,44)
(11,43)
